In [1]:
import sys
sys.path.insert(0, "../torchdriveenv")

In [12]:
!pip install pytorch-lightning

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 815.2/815.2 KB 10.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 890.6/890.6 KB 9.0 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 KB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.9/241.9 KB 13.1 MB/s eta 0:00:00
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 KB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.4/318.4 KB 15.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.9/208.9 KB 15.1 MB/s eta 0:00:00


In [2]:
import time
import torch
import torchdriveenv
from torch.utils.data import DataLoader

from datasets import TorchDriveEnvEpisodeDataset, DatasetMode
from diffusion import ConditionalDiffusionModel
from model import ConditionalResnet, ConditionalEBMDiffusionModel

/home/kezhang/work/stochastic-critic/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Commercial access denied and fallback to check for academic access.


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
data_dir = "../torchdriveenv/examples/offline_datasets/episode_data_20241025-1300"

In [5]:
dataset = TorchDriveEnvEpisodeDataset(data_dir=data_dir, mode=DatasetMode.action_state)

/home/kezhang/work/stochastic-critic/.venv/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


In [6]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [7]:
# len(dataset)

In [8]:
batch_size = 64
# data_dim = dataset.state_dim

EMA = .999

n_steps = 100
net_params = {"n_layers": 4,
              "h_dim": 128,
              "emb_dim": 32}

In [9]:
net = ConditionalResnet(n_steps=n_steps, n_layers=4, x_dim=dataset.action_dim, s_dim=dataset.state_dim, h_dim=128, emb_dim=32)

ebm_net = ConditionalEBMDiffusionModel(net)

ddpm = ConditionalDiffusionModel(dataset.action_dim, n_steps, ebm_net, device=device, var_type="beta_forward").to(device)

In [10]:
def logp_unnorm(net, ddpm, x, t, s):
    scale_e = ddpm.energy_scale(-2 - t)
    t = torch.ones((x.shape[0],)).int() * t
    return -net.neg_logp_unnorm(x, t, s) * scale_e

In [11]:
losses = []
test_logpx = []
itr = 0

ddpm.train()
optimizer = torch.optim.Adam(ddpm.parameters(), lr=1e-3)


num_steps = 200000
for itr in range(num_steps):
    ddpm.train()
    
    x, s = next(iter(dataloader))

    start_time = time.time()

    loss = ddpm.loss(x, s)
    loss = loss.mean()
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    duration_update = time.time() - start_time

    if itr % 100 == 0:
        print(itr, loss, "time:", duration_update)
        losses.append(loss)
        
    if itr % 1000 == 0:
        ddpm.eval()
        x_samp = ddpm.sample(s[0], n=1)
        print(x_samp)

0 tensor(0.4514, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.2427520751953125
tensor([[-0.9609,  1.1670]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
100 tensor(1.8725, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005777597427368164
200 tensor(0.2619, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011494159698486328
300 tensor(0.9030, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010469436645507812
400 tensor(0.3218, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010483741760253906
500 tensor(0.1691, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010981082916259766
600 tensor(0.0708, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010464191436767578
700 tensor(0.9411, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010430574417114258
800 tensor(0.0581, device='cuda:0'

6900 tensor(0.2954, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010904788970947266
7000 tensor(0.0972, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006606101989746094
tensor([[-0.4278,  0.4334]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
7100 tensor(0.0360, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010554075241088867
7200 tensor(0.0637, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01051950454711914
7300 tensor(0.0058, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011216878890991211
7400 tensor(0.4339, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011173725128173828
7500 tensor(0.0732, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011348962783813477
7600 tensor(0.4295, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.014950990676879883
7700 tensor(0.1356, dev

13700 tensor(2.4549, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.009989500045776367
13800 tensor(0.5941, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010228395462036133
13900 tensor(0.9553, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01215982437133789
14000 tensor(0.3709, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012579202651977539
tensor([[-528.5884, 1668.6140]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
14100 tensor(1.2827, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012748479843139648
14200 tensor(0.8557, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012215137481689453
14300 tensor(2.0378, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0063059329986572266
14400 tensor(0.3521, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011409521102905273
14500 tens

20500 tensor(0.1048, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010765790939331055
20600 tensor(0.1932, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011731147766113281
20700 tensor(0.0513, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011223793029785156
20800 tensor(0.0686, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005913972854614258
20900 tensor(1.2984, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005394935607910156
21000 tensor(0.6329, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01193380355834961
tensor([[-698.2582, -159.2359]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
21100 tensor(0.8512, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011414051055908203
21200 tensor(0.3170, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010582208633422852
21300 tenso

27300 tensor(0.1869, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012086629867553711
27400 tensor(0.1212, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01197052001953125
27500 tensor(0.2793, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011270761489868164
27600 tensor(0.1168, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011868953704833984
27700 tensor(0.0617, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011812210083007812
27800 tensor(0.2404, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01226949691772461
27900 tensor(1.3731, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01240682601928711
28000 tensor(0.0899, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012262344360351562
tensor([[-3.1823,  6.0901]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
28100 tensor(0.56

34100 tensor(0.0474, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01120138168334961
34200 tensor(0.0220, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011701107025146484
34300 tensor(0.1324, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011711597442626953
34400 tensor(0.9147, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010753393173217773
34500 tensor(0.0294, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011585235595703125
34600 tensor(0.0181, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006887197494506836
34700 tensor(0.0624, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012329816818237305
34800 tensor(0.1358, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011275053024291992
34900 tensor(0.2503, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010703563690185547
35

41000 tensor(0.0531, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01148366928100586
tensor([[-849.8211,  -71.0238]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
41100 tensor(0.1289, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011183977127075195
41200 tensor(0.1427, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011203765869140625
41300 tensor(0.0608, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012590169906616211
41400 tensor(0.0402, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012491464614868164
41500 tensor(0.0816, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011327028274536133
41600 tensor(0.3256, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011729717254638672
41700 tensor(3.7220, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01170206069946289
41800 tensor

47800 tensor(0.0103, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010564327239990234
47900 tensor(0.0803, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011167526245117188
48000 tensor(0.2157, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011655092239379883
tensor([[ 0.3412, -0.3025]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
48100 tensor(0.0110, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010592222213745117
48200 tensor(0.1425, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011770009994506836
48300 tensor(0.0345, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011736392974853516
48400 tensor(1.0239, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012585878372192383
48500 tensor(0.5859, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012204885482788086
48600 tensor(0

54600 tensor(0.2654, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011748313903808594
54700 tensor(2.0092, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012464284896850586
54800 tensor(0.1002, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01111745834350586
54900 tensor(0.0853, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010697364807128906
55000 tensor(0.6366, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011783599853515625
tensor([[-154968.4432,  -54261.1244]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
55100 tensor(0.2323, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01131296157836914
55200 tensor(0.1789, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011877298355102539
55300 tensor(0.1336, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013997793197631836
55400 

61400 tensor(0.0633, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01318669319152832
61500 tensor(1.0849, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011749029159545898
61600 tensor(0.0220, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011315107345581055
61700 tensor(0.0925, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011358976364135742
61800 tensor(0.0120, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011239290237426758
61900 tensor(0.0698, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01161956787109375
62000 tensor(0.0263, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010840177536010742
tensor([[-349.7042,  106.2164]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
62100 tensor(0.0615, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01243138313293457
62200 tensor(

68200 tensor(0.4012, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01177072525024414
68300 tensor(0.6390, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012234687805175781
68400 tensor(0.0466, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011801481246948242
68500 tensor(0.1357, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005252838134765625
68600 tensor(0.2910, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011273384094238281
68700 tensor(0.5221, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010763168334960938
68800 tensor(0.6242, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.007800579071044922
68900 tensor(0.0130, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.007640838623046875
69000 tensor(0.0273, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010915517807006836
te

tensor([[-0.0921,  0.1172]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
75100 tensor(0.1170, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012158393859863281
75200 tensor(0.0269, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011672258377075195
75300 tensor(0.1126, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012187957763671875
75400 tensor(0.0461, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006306886672973633
75500 tensor(0.0326, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.008344411849975586
75600 tensor(1.4518, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011914253234863281
75700 tensor(0.1602, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005410671234130859
75800 tensor(0.1916, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0061376094818115234
75900 tensor(

81900 tensor(0.0886, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013059139251708984
82000 tensor(0.0448, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012931346893310547
tensor([[ 57.5433, 224.3756]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
82100 tensor(0.0400, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012579917907714844
82200 tensor(0.1200, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011483907699584961
82300 tensor(0.0032, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011181831359863281
82400 tensor(0.0180, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010907888412475586
82500 tensor(0.0041, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010637521743774414
82600 tensor(0.0196, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011703252792358398
82700 tensor

88600 tensor(84.1154, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011986970901489258
88700 tensor(1081793.7231, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.012227773666381836
88800 tensor(466658.1457, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.0054836273193359375
88900 tensor(512439.6485, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.010901927947998047
89000 tensor(60.0391, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010971784591674805
tensor([[-608.9974,  831.4265]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
89100 tensor(49.5095, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010879993438720703
89200 tensor(444281.0323, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.012569189071655273
89300 tensor(203489.2863, device='cuda:0', dtype=torch.float64,
    

95000 tensor(406819.2784, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.013904333114624023
tensor([[ 15.7679, -23.3950]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
95100 tensor(40.0182, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01354074478149414
95200 tensor(110475.2171, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.01189732551574707
95300 tensor(77484.0461, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.011717796325683594
95400 tensor(328022.0503, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.011216402053833008
95500 tensor(26.7059, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011219501495361328
95600 tensor(41765.2144, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.011261224746704102
95700 tensor(34599.3757, device='cuda:0', dtype=torch.float64,
  

101400 tensor(888.3011, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01202392578125
101500 tensor(358.9205, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012092828750610352
101600 tensor(271.6992, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01361846923828125
101700 tensor(1520.6354, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.013507366180419922
101800 tensor(185.6003, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011156797409057617
101900 tensor(5348.2235, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.010962724685668945
102000 tensor(650.6255, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0061817169189453125
tensor([[ 1942.5561, -2614.9581]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
102100 tensor(12.0058, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) 

108000 tensor(2.2463, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012270212173461914
tensor([[ 36.1993, -41.8229]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
108100 tensor(4.4837, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011102676391601562
108200 tensor(3.8222, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010498762130737305
108300 tensor(1.7075, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006144523620605469
108400 tensor(56.0569, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011270761489868164
108500 tensor(2.2953, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011136293411254883
108600 tensor(2.0023, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010938644409179688
108700 tensor(8.7179, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012696266174316406
108

114700 tensor(6.6926, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01074528694152832
114800 tensor(3.1149, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010337591171264648
114900 tensor(13.2815, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012216806411743164
115000 tensor(2.7984, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012053728103637695
tensor([[-2745.1749,  2814.6130]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
115100 tensor(6.1101, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011977910995483398
115200 tensor(1.9121, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012549400329589844
115300 tensor(41.8811, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01373744010925293
115400 tensor(5.9380, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011574029922485352


121400 tensor(1.9277, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010489463806152344
121500 tensor(0.1235, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011464118957519531
121600 tensor(0.0460, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01157236099243164
121700 tensor(0.1693, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011452436447143555
121800 tensor(0.2527, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01197052001953125
121900 tensor(0.2821, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011500835418701172
122000 tensor(0.7669, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012615680694580078
tensor([[-81.1327, 292.8649]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
122100 tensor(1.0553, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011023283004760742
122200

128100 tensor(0.9358, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006162881851196289
128200 tensor(0.8961, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011026144027709961
128300 tensor(0.2230, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012511730194091797
128400 tensor(1.8561, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010965108871459961
128500 tensor(0.4148, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010988473892211914
128600 tensor(0.2934, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010559320449829102
128700 tensor(0.5973, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011356115341186523
128800 tensor(0.6772, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011295080184936523
128900 tensor(0.1338, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.00798153877

134900 tensor(0.0282, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006402730941772461
135000 tensor(0.0961, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013292074203491211
tensor([[ 356.9851, -421.8856]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
135100 tensor(0.2504, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005568742752075195
135200 tensor(0.0235, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.008179903030395508
135300 tensor(0.0955, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011385679244995117
135400 tensor(0.1685, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013737201690673828
135500 tensor(0.5843, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010942459106445312
135600 tensor(0.9882, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012160301208496094
13

141700 tensor(0.6572, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011014223098754883
141800 tensor(1.9523, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012953042984008789
141900 tensor(0.3661, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011802911758422852
142000 tensor(0.1514, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01147770881652832
tensor([[  279.5343, -1219.3898]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
142100 tensor(0.0450, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012041091918945312
142200 tensor(0.0533, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010828018188476562
142300 tensor(0.0584, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011567354202270508
142400 tensor(0.1245, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012192726135253906
1

148400 tensor(0.0454, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012008905410766602
148500 tensor(0.1533, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01122593879699707
148600 tensor(0.0423, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005213022232055664
148700 tensor(0.0078, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011955738067626953
148800 tensor(0.0226, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012473344802856445
148900 tensor(0.0363, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012670755386352539
149000 tensor(0.3266, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011049985885620117
tensor([[-1329.2068,  1159.1515]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
149100 tensor(0.1262, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01262354850769043
14

155100 tensor(0.2454, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013030767440795898
155200 tensor(0.0333, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0129852294921875
155300 tensor(0.0377, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012420177459716797
155400 tensor(0.0854, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011132240295410156
155500 tensor(0.0070, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010438680648803711
155600 tensor(0.0950, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013117313385009766
155700 tensor(0.0229, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012887716293334961
155800 tensor(0.0054, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013524055480957031
155900 tensor(0.0687, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0129568576812

161900 tensor(0.0182, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.005334377288818359
162000 tensor(0.1836, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006201744079589844
tensor([[ 192.4410, -639.2515]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
162100 tensor(0.0205, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006217002868652344
162200 tensor(0.1950, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011227130889892578
162300 tensor(0.1096, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011200666427612305
162400 tensor(0.4481, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010686159133911133
162500 tensor(0.9881, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010662317276000977
162600 tensor(0.1507, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01047372817993164
162

168700 tensor(0.1161, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01236724853515625
168800 tensor(11804.2858, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.012178182601928711
168900 tensor(1672.4304, device='cuda:0', dtype=torch.float64,
       grad_fn=<MeanBackward0>) time: 0.013328313827514648
169000 tensor(9.7131, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01060795783996582
tensor([[-5123.3581, 14854.5487]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
169100 tensor(0.6725, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011287689208984375
169200 tensor(79.5411, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011987924575805664
169300 tensor(16.9519, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01282811164855957
169400 tensor(2.1796, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0

175400 tensor(0.3051, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012131214141845703
175500 tensor(283.9655, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011610269546508789
175600 tensor(16.2361, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013698101043701172
175700 tensor(3.3327, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01242208480834961
175800 tensor(277.3561, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006181240081787109
175900 tensor(461.3777, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012277603149414062
176000 tensor(13.5716, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0107879638671875
tensor([[  869.2350, -2572.2193]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
176100 tensor(18.1976, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.0107853412628

182100 tensor(0.4678, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011890649795532227
182200 tensor(0.5569, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.01254582405090332
182300 tensor(0.6198, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013712167739868164
182400 tensor(0.6086, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012684106826782227
182500 tensor(0.9366, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012203454971313477
182600 tensor(0.1422, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012354373931884766
182700 tensor(0.1825, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012526273727416992
182800 tensor(0.2577, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012506723403930664
182900 tensor(0.6756, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013778448104

188900 tensor(0.6726, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012401819229125977
189000 tensor(0.0803, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006746768951416016
tensor([[17.5629, 36.7968]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
189100 tensor(0.1035, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013663530349731445
189200 tensor(0.0736, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012288570404052734
189300 tensor(0.2484, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006196498870849609
189400 tensor(0.1687, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012820243835449219
189500 tensor(0.1692, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012419939041137695
189600 tensor(0.0617, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.006575822830200195
189700

195700 tensor(0.0207, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010818958282470703
195800 tensor(0.4476, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010887861251831055
195900 tensor(0.0579, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012646675109863281
196000 tensor(0.5172, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.013301372528076172
tensor([[ -945.4844, -1700.4773]], device='cuda:0', dtype=torch.float64,
       grad_fn=<AddBackward0>)
196100 tensor(0.0669, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.010567188262939453
196200 tensor(0.1016, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.009006500244140625
196300 tensor(0.1044, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.011550188064575195
196400 tensor(0.1345, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>) time: 0.012096881866455078
